DROP TABLE IF EXISTS games CASCADE;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  cookie_uuid VARCHAR(255)
);

CREATE TABLE games(
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  link_url VARCHAR(255) NOT NULL,
  started_at TIMESTAMP DEFAULT NULL,
  ended_at TIMESTAMP DEFAULT NULL
);
