DROP TABLE IF EXISTS favourites CASCADE;
DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps(
  id SERIAL PRIMARY KEY NOT NULL,
  center VARCHAR(255) NOT NULL,
  zoom INTEGER NOT NULL,
  bounds VARCHAR(255) NOT NULL
);

CREATE TABLE favourites(
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
