DROP TABLE IF EXISTS favourites CASCADE;

DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps(
  id SERIAL PRIMARY KEY NOT NULL,
  center JSON NOT NULL,
  zoom SMALLINT NOT NULL,
  restriction JSON NOT NULL
);

CREATE TABLE favourites(
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
