DROP TABLE IF EXISTS favourites CASCADE;

DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps(
  id SERIAL PRIMARY KEY NOT NULL,
  lat SMALLINT NOT NULL,
  lng SMALLINT NOT NULL,
  zoom SMALLINT NOT NULL,
  bounds VARCHAR(255)
);

CREATE TABLE favourites(
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
